# -*- coding: utf-8 -*-
"""IR_P2_.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Gn53pNRBmdiUncDi2F1v9Nh91NCup44I

<div dir="rtl" style="font-family: Vazirmatn, Tahoma; font-size:18px; line-height:2; text-align:right; background:#f9f9f9; border-radius:10px; padding:25px; border:1px solid #ddd;">

  <p align="center" dir="rtl" style="margin-bottom: 30px;">
    <strong style="font-size: 40px;">به نام خالق هستی</strong>
  </p>

  <h3 style="font-size: 22px; color: #2c3e50;">🏛 نام دانشگاه:</h3>
  <p style="font-size: 20px;">مؤسسه آموزش عالی خراسان</p>

  <h3 style="font-size: 22px; color: #2c3e50;">📘 عنوان پروژه:</h3>
  <p style="font-size: 20px;"><strong>تحلیل داده‌های متنی Reuters-21578 و ساخت نمایه معکوس</strong></p>

  <h3 style="font-size: 22px; color: #2c3e50;">👥 اعضای گروه:</h3>
  <ul style="font-size: 20px;">
    <li>مرتضی زینل محاسبتی</li>
    <!-- Morteza GitHub -->
<li><a href="https://github.com/Mortezamohasebati" target="_blank">
  <img src="https://img.shields.io/badge/Morteza's%20GitHub-181717?style=flat&logo=github&logoColor=ffffff&labelColor=000000" alt="Morteza GitHub"/>
</a></li>
    <li>سید وحید سیدی</li>
    <!-- Vahid GitHub -->
<li><a href="https://github.com/vahidseyyedi" target="_blank">
  <img src="https://img.shields.io/badge/-Vahid's_GitHub-000000?style=flat&logo=github&logoColor=ffffff&labelColor=000000" alt="Vahid GitHub"/>
</a></li>
    <li>علی میری</li>
  </ul>

  <h3 style="font-size: 22px; color: #2c3e50;">👨‍🏫 نام استاد:</h3>
  <p style="font-size: 20px;">استاد مهدی آقایی</p>

  <h3 style="font-size: 22px; color: #2c3e50;">🎓 درس:</h3>
  <p style="font-size: 20px;">مبانی بازیابی اطلاعات</p>

</div>

<a href="https://colab.research.google.com/drive/1zORXTocsHNh7ZEuJAmaQyDxuZh_SUI-y?usp=sharing" target="_blank">
  <img src="https://img.shields.io/badge/Open%20in%20Colab-000000?style=flat&logo=googlecolab&logoColor=ffffff" alt="Open in Colab"/>
</a>

<div dir="rtl" style="font-family: Vazirmatn, Tahoma; font-size: 16px; line-height: 2; text-align: justify; background:#f9f9f9; border-radius:10px; padding:20px; border:1px solid #ddd; margin-bottom:20px;">
  <h2 style="text-align: center; font-weight: bold; margin-bottom: 15px;">مقدمه پروژه</h2>
  <p>
    در دنیای امروز، حجم عظیمی از داده‌های متنی تولید می‌شود که تحلیل آن‌ها برای استخراج دانش و اطلاعات ارزشمند، اهمیت فراوانی دارد. یکی از چالش‌های اصلی، مدیریت و بازیابی این داده‌ها به صورت مؤثر است.
  </p>
  <p>
    مجموعه داده Reuters-21578 یکی از مجموعه داده‌های استاندارد در زمینه بازیابی اطلاعات است که شامل هزاران خبر متنی می‌باشد. هدف این پروژه، پردازش و تحلیل این داده‌ها با استفاده از تکنیک‌های پردازش زبان طبیعی و ساخت نمایه معکوس است.
  </p>
  <p>
    این پروژه با استفاده از زبان برنامه‌نویسی Python و ابزارهای مرتبط انجام شده و نتایج با استفاده از نمودارهای آماری و تحلیل‌های مختلف نمایش داده شده است.
  </p>
</div>

<div dir="rtl" style="text-align:center; background:#f9f9f9; padding:20px; border-radius:12px; border:1px solid #ccc; margin:30px auto; width:90%;">
  <h3 style="color:#2c3e50; font-family:Vazirmatn,Tahoma;">🔶 نمودار جریان داده پروژه</h3>
  <img src="https://drive.google.com/uc?export=view&id=1tKbuWh2FfQEsR-WzJgmZDi7c3aFnImVQ" alt="نمودار جریان داده" style="max-width:100%; border-radius:10px; border:1px solid #bbb;">
  <p style="font-family:Vazirmatn,Tahoma; color:#333; margin-top:10px;">در این تصویر، مراحل اجرای پروژه از ورودی داده‌ها تا تحلیل نهایی نمایش داده شده است.</p>
</div>
  <a href="https://drive.google.com/file/d/1tKbuWh2FfQEsR-WzJgmZDi7c3aFnImVQ/view?usp=sharing" target="_blank">
  <img src="https://img.shields.io/badge/View%20Data%20Flow%20Diagram-24292e?style=flat&logo=google-drive&logoColor=ffffff&labelColor=24292e" alt="View Data Flow Diagram"/>
</a>

## پیش پردازش اولیه  -1
"""

import os
os.makedirs("data", exist_ok=True)
os.makedirs("stopwords", exist_ok=True)
os.makedirs("output", exist_ok=True)

"""<div dir="rtl" style="font-family: Vazirmatn, Tahoma; font-size:17px; line-height:2; text-align:right; background:#ffffff; border-radius:10px; padding:20px; border:1px solid #ccc; margin-bottom:15px;">

  <h3 style="color:#2c3e50;">
   ساختاردهی اولیه پوشه‌ها</h3>

  <p>
    در گام نخست پروژه، با هدف ساختاردهی بهتر فایل‌ها و نظم‌دهی به اجزای پروژه، سه پوشه‌ی اصلی ایجاد شد:
  </p>

  <ul>
    <li><strong>data/</strong>: برای ذخیره‌ی فایل‌های داده اصلی شامل فایل‌های <code>.sgm</code>.</li>
    <li><strong>stopwords/</strong>: شامل فایل‌های لیست کلمات توقف مانند <code>english.txt</code>.</li>
    <li><strong>output/</strong>: محل ذخیره خروجی‌های نهایی از جمله فایل‌های CSV، نمودارها و نمایه‌های معکوس.</li>
  </ul>

  <p>
    این پوشه‌ها با استفاده از کتابخانه <code>os</code> و تابع <code>()os.makedirs</code> ایجاد شدند تا در صورت اجرای مجدد، خطایی در صورت وجود قبلی پوشه‌ها رخ ندهد (به کمک پارامتر <code>exist_ok=True</code>).
  </p>

  <p style="background:#f5f5f5; border:1px dashed #ccc; padding:10px; border-radius:6px;">
    این ساختار استاندارد باعث می‌شود فایل‌های مختلف پروژه به‌صورت طبقه‌بندی‌شده نگهداری شده و از شلوغی در فضای کاری جلوگیری شود.
  </p>

</div>

"""

!mkdir -p data stopwords output
!wget -P data http://kdd.ics.uci.edu/databases/reuters21578/reuters21578.tar.gz
!tar -xvzf data/reuters21578.tar.gz -C data
!wget -P stopwords https://raw.githubusercontent.com/Alir3z4/stop-words/master/english.txt

"""<div dir="rtl" style="font-family: Vazirmatn, Tahoma; font-size:17px; line-height:2; text-align:right; background:#ffffff; border-radius:10px; padding:20px; border:1px solid #ccc; margin-bottom:15px;">

  <h3 style="color:#2c3e50;"> دانلود و استخراج داده‌ها</h3>

  <p>
    در این مرحله، داده‌های اصلی مورد نیاز پروژه شامل مجموعه‌ی Reuters-21578 از منبع دانشگاه کالیفرنیا (UCI) و لیست کلمات توقف زبان انگلیسی از گیت‌هاب دریافت شدند.
  </p>

  <ul>
    <li>فایل فشرده <code>reuters21578.tar.gz</code> به کمک ابزار <code>wget</code> در پوشه <strong>data/</strong> دانلود شد.</li>
    <li>پس از دانلود، با دستور <code>tar -xvzf</code> فایل‌ها استخراج و مستقیماً در مسیر <strong>data/</strong> قرار گرفتند.</li>
    <li>فایل <code>english.txt</code> که شامل لیستی از کلمات توقف است، در پوشه <strong>stopwords/</strong> ذخیره شد.</li>
  </ul>

  <p style="background:#f9f9f9; border:1px dashed #aaa; padding:12px; border-radius:8px;">
    استفاده از ساختار پوشه‌ای باعث شد تا داده‌های خام و فایل‌های کمکی پروژه به طور منظم و مجزا ذخیره شوند و امکان پردازش آسان‌تر در مراحل بعدی فراهم شود.
  </p>

</div>

"""

!pip install beautifulsoup4 lxml nltk seaborn
!pip install keybert

"""<div dir="rtl" style="font-family: Vazirmatn, Tahoma; font-size:17px; line-height:2; text-align:right; background:#ffffff; border-radius:10px; padding:20px; border:1px solid #ccc; margin-bottom:15px;">

  <h3 style="color:#2c3e50;"> نصب کتابخانه‌های مورد نیاز</h3>

  <p>
    برای اجرای پردازش‌های متنی و تحلیل داده‌ها، برخی کتابخانه‌های پایتون که در محیط Google Colab ممکن است نصب نباشند، به کمک دستور <code>pip install</code> نصب شدند.
  </p>

  <ul>
    <li><strong>beautifulsoup4:</strong> برای تجزیه و استخراج داده‌ها از فایل‌های HTML/XML (مثل فایل‌های SGM).</li>
    <li><strong>lxml:</strong> یک موتور تجزیه سریع و کارآمد برای BeautifulSoup.</li>
    <li><strong>nltk:</strong> یکی از معروف‌ترین کتابخانه‌های پردازش زبان طبیعی (Natural Language Processing).</li>
    <li><strong>seaborn:</strong> برای ترسیم نمودارهای آماری زیبا و تحلیلی.</li>
  </ul>

  <p style="background:#f9f9f9; border:1px dashed #aaa; padding:12px; border-radius:8px;">
    این کتابخانه‌ها زیربنای اصلی پروژه هستند و در مراحل مختلف مانند توکن‌سازی، حذف کلمات توقف، استمینگ، تجزیه متون و ترسیم نمودارهای تحلیلی مورد استفاده قرار می‌گیرند.
  </p>

</div>

"""

import os
import re
from bs4 import BeautifulSoup
from nltk.stem import PorterStemmer
from collections import OrderedDict
import csv
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns
from sklearn.decomposition import PCA
import nltk
nltk.download('wordnet')
from nltk.corpus import wordnet
import copy
from itertools import combinations

"""<div dir="rtl" style="font-family: Vazirmatn, Tahoma; font-size:17px; line-height:2; text-align:right; background:#ffffff; border-radius:10px; padding:20px; border:1px solid #ccc; margin-bottom:15px;">

  <h3 style="color:#2c3e50;">
  وارد کردن کتابخانه‌ها و آماده‌سازی اولیه</h3>

  <p>
    در ابتدای پروژه، مجموعه‌ای از کتابخانه‌های ضروری برای پردازش متون، استخراج داده‌ها و تحلیل آماری فراخوانی شده‌اند. این مرحله پایه و اساس تحلیل‌های بعدی را فراهم می‌کند:
  </p>

  <ul>
    <li><strong>os، re:</strong> برای مدیریت مسیر فایل‌ها و اعمال عبارات منظم جهت پاک‌سازی متن.</li>
    <li><strong>BeautifulSoup:</strong> جهت تجزیه و استخراج اطلاعات از فایل‌های SGM با ساختار XML مانند.</li>
    <li><strong>nltk:</strong> برای انجام عملیات پردازش زبان طبیعی مانند استمینگ، توکن‌سازی و استفاده از WordNet.</li>
    <li><strong>PorterStemmer:</strong> پیاده‌سازی الگوریتم معروف استمر پرتر برای ریشه‌یابی کلمات انگلیسی.</li>
    <li><strong>wordnet:</strong> دیتابیس معنایی واژگان که برای فیلتر کردن کلمات نامعتبر استفاده شده است.</li>
    <li><strong>OrderedDict:</strong> ساختار دیکشنری مرتب‌شده که برای نگه‌داری ترتیب واژگان در نمایه معکوس به کار رفته است.</li>
    <li><strong>csv:</strong> برای ذخیره خروجی‌ها (توکن‌ها، نمایه‌ها و ...) به‌صورت فایل‌های قابل تحلیل با نرم‌افزارهای آماری.</li>
    <li><strong>matplotlib، seaborn:</strong> برای ترسیم نمودارهای مختلف مانند هیتمپ، جعبه‌ای، پراکندگی و دایره‌ای.</li>
    <li><strong>sklearn.decomposition.PCA:</strong> ماژولی برای کاهش ابعاد داده‌ها و نمایش تصویری بهتر ماتریس ترم‌ها.</li>
    <li><strong>copy، combinations:</strong> برای ایجاد کپی امن از دیکشنری‌ها و ترکیب جفتی روش‌ها در تحلیل‌های مقایسه‌ای.</li>
    <li><strong>nltk.download('wordnet'):</strong> دانلود دیتابیس WordNet برای بررسی معنای واژگان در روش دوم.</li>
  </ul>

  <p style="background:#f9f9f9; border:1px dashed #aaa; padding:12px; border-radius:8px;">
    این مجموعه کتابخانه‌ها نقش ستون فقرات پروژه را دارند و در تمامی مراحل از آماده‌سازی داده‌ها تا استخراج اطلاعات و مصورسازی به‌کار رفته‌اند.
  </p>

</div>

"""

class ReutersArticle:
  def __init__(self ,file_name , newid , topics , title , body , tokens):
    self.file_name = file_name
    self.newid = newid
    self.topics = topics
    self.title = title
    self.body = body
    self.tokens = tokens

  def __repr__(self):
    return(f"file_name:{self.file_name} , newID:{self.newid} , topics:{self.topics} , title:{self.title} , body:{self.body} , tokens:{self.tokens}")

"""<div dir="rtl" style="font-family: Vazirmatn, Tahoma; font-size:17px; line-height:2; text-align:right; background:#ffffff; border-radius:10px; padding:20px; border:1px solid #ccc; margin-bottom:15px;">

  <h3 style="color:#2c3e50;">  تعریف کلاس داده‌ای <code>ReutersArticle</code></h3>

  <p>
    در این مرحله، یک کلاس شی‌ءگرا به نام <code>ReutersArticle</code> طراحی شد تا اطلاعات هر مقاله در ساختار منظم‌تری ذخیره شود. این ساختار برای پردازش‌های بعدی بسیار مفید خواهد بود.
  </p>

  <p>ویژگی‌های تعریف‌شده در این کلاس عبارت‌اند از:</p>

  <ul>
    <li><strong>file_name:</strong> نام فایل .sgm که مقاله در آن قرار دارد.</li>
    <li><strong>newid:</strong> شناسه یکتای مقاله (ویژگی موجود در تگ reuters).</li>
    <li><strong>topics:</strong> لیستی از موضوعات مقاله.</li>
    <li><strong>title:</strong> عنوان مقاله.</li>
    <li><strong>body:</strong> بدنه اصلی متن مقاله.</li>
    <li><strong>tokens:</strong> توکن‌های تولیدشده از متن مقاله (در مراحل بعدی).</li>
  </ul>

  <p>
    همچنین متد <code>__repr__</code> بازنویسی شده تا بتوان خروجی خلاصه و قابل‌فهمی از اشیای این کلاس در کنسول دریافت کرد.
  </p>

  <p style="background:#f9f9f9; border:1px dashed #aaa; padding:12px; border-radius:8px;">
    استفاده از این ساختار کلاس‌بندی‌شده، خوانایی کد را افزایش داده و دسترسی به اطلاعات مقاله‌ها را در مراحل مختلف پروژه ساده‌تر می‌کند.
  </p>

</div>

"""

def extract_articles_with_topics(file_path):
    with open(file_path, 'r', encoding='latin-1') as file:
        data = file.read()
        data = data.replace('&#2;', '').replace('&#3;', '')
        soup = BeautifulSoup(data, 'html.parser')
        all_articles = soup.find_all('reuters')
        articles_yes = [a for a in all_articles if a.get('topics') == 'YES']
        return articles_yes, len(all_articles)

"""<div dir="rtl" style="font-family: Vazirmatn, Tahoma; font-size:17px; line-height:2; text-align:right; background:#ffffff; border-radius:10px; padding:20px; border:1px solid #ccc; margin-bottom:15px;">

  <h3 style="color:#2c3e50;">  استخراج مقالات دارای موضوع (topics="YES")</h3>

  <p>
    در این مرحله، یک تابع به نام <code>extract_articles_with_topics</code> پیاده‌سازی شده است تا تنها مقالاتی را استخراج کند که دارای برچسب <code>topics="YES"</code> هستند.
  </p>

  <p>شرح عملکرد تابع:</p>
  <ul>
    <li>باز کردن فایل <code>.sgm</code> با رمزگذاری <code>latin-1</code>.</li>
    <li>حذف کاراکترهای مزاحم </li>
    <li>استفاده از کتابخانه <code>BeautifulSoup</code> برای پارس کردن محتوای فایل.</li>
    <li>یافتن تمام تگ‌های <code>reuters</code>.</li>
    <li>فیلتر کردن مقالاتی که ویژگی <code>topics="YES"</code> دارند.</li>
  </ul>

  <p>
    خروجی این تابع شامل دو مقدار است:
  </p>
  <ol>
    <li>لیستی از مقالات دارای موضوع.</li>
    <li>تعداد کل مقالات موجود در فایل.</li>
  </ol>

  <p style="background:#f9f9f9; border:1px dashed #aaa; padding:12px; border-radius:8px;">
    این گام ابتدایی، مسیر را برای تحلیل‌های دقیق‌تر روی مقالات معنادار هموار می‌سازد و مقالات بدون موضوع را کنار می‌گذارد.
  </p>

</div>

"""

def data_parser(article):
    newid = int(article['newid'])
    topics_tag = article.find('topics')
    title_tag = article.find('title')
    body_tag = article.find('body')

    topics = [d.get_text() for d in topics_tag.find_all('d')] if topics_tag else []
    title = title_tag.get_text() if title_tag else ""
    body = body_tag.get_text() if body_tag else ""

    return newid, topics, title, body

"""<div dir="rtl" style="font-family: Vazirmatn, Tahoma; font-size:17px; line-height:2; text-align:right; background:#ffffff; border-radius:10px; padding:20px; border:1px solid #ccc; margin-bottom:15px;">

  <h3 style="color:#2c3e50;">  تجزیه و استخراج اطلاعات هر مقاله</h3>

  <p>
    در این مرحله، تابعی به نام <code>data_parser</code> طراحی شده است تا از هر مقاله استخراج‌شده، اطلاعات کلیدی زیر را بازیابی کند:
  </p>

  <ul>
    <li><strong>newid:</strong> شناسه یکتا مقاله (مقداری عددی)</li>
    <li><strong>topics:</strong> لیستی از موضوعات مشخص شده در تگ <code>&lt;topics&gt;</code></li>
    <li><strong>title:</strong> عنوان مقاله در صورت وجود</li>
    <li><strong>body:</strong> بدنه یا محتوای اصلی مقاله (متن مقاله)</li>
  </ul>

  <p>
    اگر هر یک از بخش‌های <code>&lt;topics&gt;</code>، <code>&lt;title&gt;</code> یا <code>&lt;body&gt;</code> در مقاله موجود نباشند، مقدار پیش‌فرض آن‌ها به صورت رشتهٔ خالی <code>""</code> در نظر گرفته می‌شود تا از بروز خطا در اجرای برنامه جلوگیری شود.
  </p>

  <p style="background:#f9f9f9; border:1px dashed #aaa; padding:12px; border-radius:8px;">
    این تابع برای تبدیل هر مقاله از ساختار XML به یک قالب قابل پردازش پایتونی کاربرد دارد و نقش مهمی در آماده‌سازی داده‌ها ایفا می‌کند.
  </p>

</div>

"""

def update_file_state(file_name, first, current_len, total , empty_body):
    last = current_len - 1
    topic_stats[file_name] = {
        "first": first,
        "last": last,
        "length": last - first + 1,
        "total_articles": total,
        "yes": last - first + 1,
        "no": total - (last - first + 1),
        "empty_body": empty_body
    }

"""<div dir="rtl" style="font-family: Vazirmatn, Tahoma; font-size:17px; line-height:2; text-align:right; background:#ffffff; border-radius:10px; padding:20px; border:1px solid #ccc; margin-bottom:15px;">

  <h3 style="color:#2c3e50;">  به‌روزرسانی وضعیت فایل‌ها و محاسبه آمار مقالات</h3>

  <p>
    در این بخش، از تابع <code>update_file_state</code> برای ثبت وضعیت آماری هر فایل SGM استفاده شده است. این اطلاعات در دیکشنری‌ای به نام <code>topic_stats</code> ذخیره می‌شود تا تحلیل آماری دقیقی در مراحل بعد امکان‌پذیر باشد.
  </p>

  <p>این تابع پارامترهای زیر را دریافت می‌کند:</p>
  <ul>
    <li><strong>file_name:</strong> نام فایل ورودی (مثلاً reut2-000.sgm)</li>
    <li><strong>first:</strong> ایندکس اولین مقاله با topic="YES" در دیکشنری کلی</li>
    <li><strong>current_len:</strong> طول فعلی دیکشنری مقالات پس از پردازش فایل</li>
    <li><strong>total:</strong> تعداد کل مقالات موجود در فایل</li>
    <li><strong>empty_body:</strong> تعداد مقالاتی که بدنه (BODY) ندارند</li>
  </ul>

  <p>مقادیر محاسبه‌شده در هر فایل شامل موارد زیر هستند:</p>
  <ul>
    <li><strong>first / last:</strong> ایندکس شروع و پایان مقالات مرتبط در دیکشنری اصلی</li>
    <li><strong>length:</strong> تعداد مقالات دارای topic="YES"</li>
    <li><strong>yes / no:</strong> تعداد مقالات با و بدون موضوع (topic)</li>
    <li><strong>empty_body:</strong> مقالاتی که بدنه آن‌ها تهی است</li>
  </ul>

  <p style="background:#f9f9f9; border:1px dashed #aaa; padding:12px; border-radius:8px;">
    این ساختار آماری در مراحل بعدی پروژه از جمله ترسیم نمودارهای میله‌ای و دایره‌ای به‌عنوان منبع اصلی داده‌ها مورد استفاده قرار خواهد گرفت.
  </p>

</div>

"""

folder_path = "data"
all_articles = {}
topic_stats = {}
counter_id = 0
counter_body = 0
for i in range(22):
    file_name = f"reut2-{i:03}.sgm"
    file_path = os.path.join(folder_path, file_name)

    first_index = len(all_articles)
    articles_yes, total_articles = extract_articles_with_topics(file_path)

    for article in articles_yes:
        newid, topics, title, body = data_parser(article)
        all_articles[counter_id] = ReutersArticle(i, newid, topics, title, body, [])
        counter_id += 1
        if not body or body.strip() == "":
            counter_body += 1

    update_file_state(file_name, first_index, len(all_articles), total_articles , counter_body)
    counter_body = 0

"""<div dir="rtl" style="font-family: Vazirmatn, Tahoma; font-size:17px; line-height:2; text-align:right; background:#ffffff; border-radius:10px; padding:20px; border:1px solid #ccc; margin-bottom:15px;">

  <h3 style="color:#2c3e50;">  پردازش فایل‌های SGM و استخراج مقالات دارای موضوع</h3>

  <p>
    در این مرحله، تمامی فایل‌های داده‌ای موجود در پوشه <code>data/</code> به‌صورت حلقه پردازش می‌شوند. تعداد فایل‌ها ۲۲ عدد است که با فرمت <code>reut2-XXX.sgm</code> نام‌گذاری شده‌اند.
  </p>

  <p>مراحل انجام‌شده در این بخش:</p>
  <ol>
    <li>تعریف دیکشنری‌ها و شمارنده‌های مورد نیاز: <code>all_articles</code> برای ذخیره مقالات، <code>topic_stats</code> برای آمار فایل‌ها، و شمارنده‌های داخلی.</li>
    <li>برای هر فایل:</li>
    <ul>
      <li>خواندن مقالات دارای موضوع (topic="YES") با استفاده از تابع <code>extract_articles_with_topics</code></li>
      <li>پردازش هر مقاله: استخراج شناسه، موضوعات، عنوان و بدنه با تابع <code>data_parser</code></li>
      <li>ساخت شیء <code>ReutersArticle</code> و ذخیره در دیکشنری <code>all_articles</code> با شناسه متمایز</li>
      <li>شمارش مقالات بدون بدنه برای آمار دقیق‌تر</li>
      <li>به‌روزرسانی وضعیت آماری فایل در دیکشنری <code>topic_stats</code> با تابع <code>update_file_state</code></li>
    </ul>
  </ol>

  <p style="background:#f9f9f9; border:1px dashed #aaa; padding:12px; border-radius:8px;">
    در نهایت دیکشنری <code>all_articles</code> شامل همه مقالات دارای موضوع است و <code>topic_stats</code> حاوی آمار جزئی و دقیق برای هر فایل می‌باشد. این داده‌ها مبنای مراحل بعدی تحلیل و مصورسازی هستند.
  </p>

</div>

"""

def print_sample_dic(dict, start, end):
    print("\n Dictionary details:\n")
    li = list(dict.items())
    for i , j in li[start:end]:
        print(f"ID: {i}")
        print(j)

"""<div dir="rtl" style="font-family: Vazirmatn, Tahoma; font-size:17px; line-height:2; text-align:right; background:#ffffff; border-radius:10px; padding:20px; border:1px solid #ccc; margin-bottom:15px;">

  <h3 style="color:#2c3e50;"> تابع print_sample_dic - نمایش نمونه‌ای از دیکشنری</h3>

  <p>
    این تابع برای نمایش نمونه‌ای از داده‌های ذخیره شده در یک دیکشنری کاربرد دارد. با دادن محدوده‌ی شروع و پایان، بخش مشخصی از دیکشنری به صورت مرتب چاپ می‌شود.
  </p>

  <p>روش کار تابع:</p>
  <ol>
    <li>تبدیل دیکشنری ورودی به لیستی از زوج‌های کلید-مقدار با استفاده از <code>list(dict.items())</code>.</li>
    <li>حلقه روی زوج‌های مشخص شده در بازه <code>start</code> تا <code>end</code>.</li>
    <li>نمایش کلید و مقدار مربوطه با فرمت خوانا در خروجی کنسول.</li>
  </ol>

  <p style="background:#f9f9f9; border:1px dashed #aaa; padding:12px; border-radius:8px;">
    این تابع برای بررسی سریع و نمونه‌برداری از داده‌های بزرگ بسیار مفید است و امکان بازبینی دستی محتویات دیکشنری را فراهم می‌کند.
  </p>

</div>

"""

print_sample_dic(topic_stats , 0 , len(topic_stats))

"""<div dir="rtl" style="font-family: Vazirmatn, Tahoma; font-size:17px; line-height:2; text-align:right; background:#fff; border-radius:10px; padding:20px; border:1px solid #ccc; margin-bottom:15px;">
  <h3> نمایش کامل آمار موضوعات (topic_stats)</h3>
  <p>با اجرای کد زیر، کل داده‌های مربوط به وضعیت فایل‌ها و تعداد مقالات دارای موضوع استخراج شده و نمایش داده می‌شود:</p>
  <pre style="background:#f4f4f4; padding:10px; border-radius:6px;">print_sample_dic(topic_stats, 0, len(topic_stats))</pre>
  <p>خروجی این تابع، اطلاعات آماری دقیق درباره تعداد مقالات، مقالات با موضوع، مقالات بدون بدنه و ... را به صورت مرتب چاپ می‌کند.</p>
</div>

"""

print_sample_dic(all_articles , 18 , 21)

"""<div dir="rtl" style="font-family: Vazirmatn, Tahoma; font-size:17px; line-height:2; text-align:right; background:#fff; border-radius:10px; padding:20px; border:1px solid #ccc; margin-bottom:15px;">
  <h3> نمونه مقالات استخراج شده (ID: 18 تا 20)</h3>
  <p>با اجرای دستور زیر، جزئیات مقالات با شناسه‌های ۱۸ تا ۲۰ از دیکشنری مقالات چاپ می‌شود:</p>
  <pre style="background:#f4f4f4; padding:10px; border-radius:6px;">
print_sample_dic(all_articles, 18, 21)</pre>
  <p>خروجی شامل فیلدهایی مثل شناسه فایل، newid، موضوعات، عنوان، متن و توکن‌های مقاله است.</p>
</div>

"""

def autopct_func(slices):
    def inner(pct):
        total = sum(slices)
        val = int(round(pct * total / 100.0))
        return f"{pct:.1f}%\n({val})"
    return inner

def show_dual_pie_chart(slices1, labels1, title1,
                        slices2, labels2, title2):
    fig, axs = plt.subplots(1, 2, figsize=(12, 6))  # 1 row, 2 columns

    # Pie Chart 1
    axs[0].pie(slices1, labels=labels1,
               wedgeprops={'edgecolor': 'black'},
               startangle=45, shadow=True,
               autopct=autopct_func(slices1))
    axs[0].set_title(title1)

    # Pie Chart 2
    axs[1].pie(slices2, labels=labels2,
               wedgeprops={'edgecolor': 'black'},
               startangle=45, shadow=True,
               autopct=autopct_func(slices2))
    axs[1].set_title(title2)

    plt.tight_layout()
    plt.show()

total_yes = sum(item['yes'] for item in topic_stats.values())
total_no = sum(item['no'] for item in topic_stats.values())
slices1 = [total_yes, total_no]
labels1 = ["Yes", "No"]

empty_body = sum(item['empty_body'] for item in topic_stats.values())
yes = total_yes - empty_body
slices2 = [yes, total_no, empty_body]
labels2 = ["Yes", "No", "Yes: empty body"]

show_dual_pie_chart(slices1, labels1, "Overall Topic Distribution",
                    slices2, labels2, "Yes Split: Empty Body")

"""<div dir="rtl" style="font-family: Vazirmatn, Tahoma; font-size:18px; line-height:2; text-align:right; background:#f9f9f9; border-radius:10px; padding:20px; border:1px solid #ddd; margin-top:20px;">

  <h3>  رسم و تحلیل نمودارهای دایره‌ای برای بررسی مقالات</h3>

  <p>
    در این بخش از پروژه، برای تحلیل آماری داده‌ها از نمودارهای دایره‌ای استفاده شده است. ابتدا با استفاده از تابع <code>autopct_func</code> فرمت مناسبی برای نمایش درصد و مقدار واقعی هر برش دایره طراحی شد. سپس با تابع <code>show_dual_pie_chart</code> دو نمودار دایره‌ای به‌صورت هم‌زمان رسم شدند.
  </p>

  <p>
    هدف از این نمودارها، بررسی توزیع مقالات دارای برچسب <code>topics="YES"</code> و مقالات بدون برچسب (NO) در کنار بررسی دقیق‌تر مقالات YES ولی بدون محتوای متنی (بدنه) است.
  </p>

  <ul>
    <li><strong>نمودار سمت راست:</strong> نسبت کلی مقالات YES و NO.</li>
    <li><strong>نمودار سمت چپ:</strong> تقسیم مقالات YES به دو دسته دارای بدنه و بدون بدنه، در کنار مقالات NO.</li>
  </ul>

  <p>
    این تحلیل گرافیکی باعث شد دید بهتری نسبت به کیفیت و ساختار محتوای متون موجود در پایگاه داده پیدا کنیم و مشخص شود که بخشی از مقالات برچسب‌دار فاقد متن (Body) هستند که می‌تواند در دقت بازیابی اطلاعات تأثیر منفی بگذارد.
  </p>

</div>

"""

def show_chart_bar(x1, y1, y2, y3, l1="all", l2="yes", l3="empty body"):
    x = np.arange(len(x1))
    w = 0.25

    plt.figure(figsize=(12, 6))

    bars1 = plt.bar(x, y1, width=w, label=l1)
    bars2 = plt.bar(x + w, y2, width=w, label=l2)
    bars3 = plt.bar(x + 2*w, y3, width=w, label=l3)

    for bar in bars1:
        height = bar.get_height()
        if height > 0:
            plt.text(bar.get_x() + bar.get_width()/2, height + 1, f'{int(height)}', ha='center', va='bottom', fontsize=8)

    for bar in bars2:
        height = bar.get_height()
        if height > 0:
            plt.text(bar.get_x() + bar.get_width()/2, height + 1, f'{int(height)}', ha='center', va='bottom', fontsize=8)

    for bar in bars3:
        height = bar.get_height()
        if height > 0:
            plt.text(bar.get_x() + bar.get_width()/2, height + 1, f'{int(height)}', ha='center', va='bottom', fontsize=8)

    plt.legend()
    plt.title("Topics per file")
    plt.xlabel("Files")
    plt.ylabel("Number of topics")
    plt.xticks(x + w, x1, rotation=90)
    plt.tight_layout()
    plt.show()

show_chart_bar(
    list(topic_stats.keys()),
    [item['total_articles'] for item in topic_stats.values()],
    [item['yes'] for item in topic_stats.values()],
    [item['empty_body'] for item in topic_stats.values()]
)

"""<div dir="rtl" style="font-family: Vazirmatn, Tahoma; font-size:18px; line-height:2; text-align:right; background:#f9f9f9; border-radius:10px; padding:20px; border:1px solid #ddd; margin-top:20px;">

  <h3>  تحلیل مقایسه‌ای تعداد مقالات با نمودار میله‌ای</h3>

  <p>
    به منظور مقایسه‌ی آماری فایل‌های مختلف مجموعه داده <code>Reuters-21578</code> از لحاظ تعداد مقالات، مقالات دارای برچسب <code>topics="YES"</code>، و همچنین مقالات بدون بدنه (Body)، یک نمودار میله‌ای طراحی شد.
  </p>

  <p>
    این نمودار با استفاده از تابع <code>show_chart_bar</code> رسم شده است که سه گروه داده را به‌صورت میله‌های موازی نمایش می‌دهد:
  </p>

  <ul>
    <li><strong>میله‌های آبی:</strong> تعداد کل مقالات موجود در هر فایل.</li>
    <li><strong>میله‌های نارنجی:</strong> تعداد مقالات دارای برچسب YES در همان فایل.</li>
    <li><strong>میله‌های سبز:</strong> تعداد مقالات YES که فاقد بدنه متنی هستند.</li>
  </ul>

  <p>
    این تحلیل به ما کمک می‌کند تا فایل‌هایی که بیشترین مقالات یا بیشترین مقالات ناقص را دارند، به‌راحتی شناسایی کنیم. همچنین اعداد بالای هر میله با استفاده از توابع کمکی به صورت خوانا و دقیق نمایش داده شده‌اند که دقت بصری نمودار را افزایش می‌دهد.
  </p>

  <p>
    چنین تجزیه و تحلیل‌هایی در ارزیابی کیفیت داده و تصمیم‌گیری در مراحل بعدی پردازش و مدل‌سازی بسیار مفید است.
  </p>

</div>

"""

class PostingList:
    def __init__(self):
        self.data_list = []
        self.doc_ids = set()
        self.total_tf = 0

    def add(self, doc_id, tf=1):
        for i, (d_id, count) in enumerate(self.data_list):
            if d_id == doc_id:
                self.data_list[i] = (d_id, count + tf)
                self.total_tf += tf
                return
        self.data_list.append((doc_id, tf))
        self.doc_ids.add(doc_id)
        self.total_tf += tf

    def __repr__(self):
        return (
            f"docs: {sorted(self.doc_ids)} , "
            f"DF: {len(self.doc_ids)} , "
            f"TTF: {self.total_tf} , "
            f"data: {self.data_list}"
        )

"""<div dir="rtl" style="font-family: Vazirmatn, Tahoma; font-size:18px; line-height:2; text-align:right; background:#fefefe; border-radius:10px; padding:20px; border:1px solid #ccc; margin-top:20px;">

  <h3 style="color:#005580;">  ساختار کلاس PostingList</h3>

  <p>
    در این بخش، یک کلاس به نام <code><strong>PostingList</strong></code> تعریف شده است که برای ساخت نمایه معکوس استفاده می‌شود. این کلاس به ازای هر واژه، لیستی از اسناد و فراوانی آن را ذخیره می‌کند. ساختار این کلاس شامل ویژگی‌ها و توابع زیر است:
  </p>

  <ul>
    <li><strong>data_list:</strong> یک لیست از تاپل‌های (شماره سند، فراوانی واژه در آن سند).</li>
    <li><strong>doc_ids:</strong> یک مجموعه برای ذخیره یکتا از شماره اسناد حاوی واژه.</li>
    <li><strong>total_tf:</strong> فراوانی کلی واژه در کل مجموعه اسناد (TTF).</li>
    <li><strong>()add:</strong> این متد، واژه را به لیست اسناد اضافه کرده و در صورت وجود، فراوانی را به‌روزرسانی می‌کند.</li>
    <li><strong>__repr__:</strong> متدی برای نمایش ساختار اطلاعاتی کلاس به صورت خوانا (شامل لیست اسناد، تعداد اسناد، و مجموع فراوانی).</li>
  </ul>

  <p>
    این ساختار باعث می‌شود که برای هر واژه بتوان به‌سادگی به لیست اسناد حاوی آن و اطلاعات آماری مرتبط دسترسی داشت.
  </p>

</div>

"""

def tokenize_articles(articles_dict, tokenizer_func):
    for article in articles_dict.values():
        article.tokens = tokenizer_func(article.body)
        article.body = ""

"""<div dir="rtl" style="font-family: Vazirmatn, Tahoma; font-size:18px; line-height:2; text-align:right; background:#fefefe; border-radius:10px; padding:20px; border:1px solid #ccc; margin-top:20px;">

  <h3 style="color:#005580;">  تابع <code>tokenize_articles</code></h3>

  <p>
    این تابع، فرآیند توکن‌سازی (شکستن متن به کلمات یا عبارات معنی‌دار) را بر روی بدنه مقالات انجام می‌دهد. در ابتدا دیکشنری حاوی مقالات دریافت می‌شود و برای هر مقاله، متن موجود در بخش <code>body</code> با استفاده از تابع توکن‌ساز مشخص‌شده پردازش می‌شود.
  </p>

  <p>
    خروجی توکن‌ساز در فیلد <code>tokens</code> مقاله ذخیره شده و سپس مقدار فیلد <code>body</code> حذف (خالی) می‌شود تا حافظه اشغال‌شده توسط متن اولیه آزاد گردد و ساختار داده‌ای ساده‌تر و سبک‌تری شکل بگیرد.
  </p>

  <p>
    این مرحله پیش‌نیازی مهم برای ساخت نمایه معکوس و محاسبه آماره‌های متنی است، زیرا تحلیل‌های بعدی صرفاً بر اساس توکن‌ها انجام می‌گیرد.
  </p>

</div>

"""

def save_dict_to_csv(articles_dict, path):
    with open(path , mode="w",newline="") as file:
         writer = csv.writer(file)
         writer.writerow(["word" , "postings"])
         for key, value in articles_dict.items():
             writer.writerow([key, str(value)])

"""<div dir="rtl" style="font-family: Vazirmatn, Tahoma; font-size:18px; line-height:2; text-align:right; background:#fefefe; border-radius:10px; padding:20px; border:1px solid #ccc; margin-top:20px;">

  <h3 style="color:#005580;">  تابع <code>save_dict_to_csv</code></h3>

  <p>
    این تابع وظیفه ذخیره‌سازی اطلاعات موجود در یک دیکشنری به‌صورت فایل CSV را بر عهده دارد. هدف از این مرحله، آرشیو داده‌ها برای استفاده‌های بعدی مانند تحلیل آماری، مستندسازی یا بارگذاری در نرم‌افزارهایی مانند Excel است.
  </p>

  <p>
    در ابتدا یک فایل CSV در مسیر مشخص‌شده ایجاد می‌شود و دو ستون با عنوان‌های «word» و «postings» در ردیف اول نوشته می‌شود. سپس با پیمایش دیکشنری، کلیدها (که معمولاً کلمات هستند) و مقادیرشان (که اغلب ساختار لیستی از موقعیت یا تکرار آن کلمه در اسناد است) به‌صورت رشته در فایل ذخیره می‌شوند.
  </p>

  <p>
    این تابع برای ذخیره‌ی خروجی‌هایی مانند لیست توکن‌ها، نمایه معکوس یا سایر دیکشنری‌های آماری بسیار کاربردی است.
  </p>

</div>

"""

def build_inverted_index(articles_dict):
    matrix_words={}
    for file_id, data in articles_dict.items():
        for word in data.tokens:
            if word not in matrix_words:
               matrix_words[word] = PostingList()
            matrix_words[word].add(data.file_name, 1)
    return matrix_words

"""<div dir="rtl" style="font-family: Vazirmatn, Tahoma; font-size:18px; line-height:2; text-align:right; background:#fefefe; border-radius:10px; padding:20px; border:1px solid #ccc; margin-top:20px;">

  <h3 style="color:#005580;">  ساخت نمایه معکوس</h3>

  <p>
    در این مرحله، هدف اصلی ساخت یک <strong>نمایه معکوس (Inverted Index)</strong> از مجموعه مقالات پردازش‌شده است. این نمایه، ارتباط بین هر واژه و فهرست مقالاتی که آن واژه در آن‌ها ظاهر شده را ذخیره می‌کند.
  </p>

  <p>
    برای هر مقاله موجود در دیکشنری ورودی، تمام توکن‌های آن مقاله بررسی می‌شوند. سپس اگر واژه‌ای قبلاً در نمایه وجود نداشته باشد، یک شیء جدید از کلاس <code>PostingList</code> برای آن ایجاد می‌شود. سپس با استفاده از متد <code>add</code>، شماره فایل مقاله و تکرار آن واژه در نمایه ذخیره می‌شود.
  </p>

  <p>
    خروجی این تابع، دیکشنری‌ای است که کلیدهای آن واژه‌ها و مقادیر آن‌ها، اشیاء <code>PostingList</code> هستند. این ساختار پایه‌ای برای محاسبات آماری بعدی مانند <strong>TF، DF و TTF</strong> خواهد بود و در نمایش نهایی نمایه معکوس مورد استفاده قرار می‌گیرد.
  </p>

</div>

"""

def sort_inverted_index(matrix_words):
    return OrderedDict(sorted(matrix_words.items(), key=lambda item: item[0]))

"""<div dir="rtl" style="font-family: Vazirmatn, Tahoma; font-size:18px; line-height:2; text-align:right; background:#fefefe; border-radius:10px; padding:20px; border:1px solid #ccc; margin-top:20px;">

  <h3 style="color:#005580;">  مرتب‌سازی نمایه معکوس</h3>

  <p>
    پس از ساخت نمایه معکوس، ممکن است واژه‌ها به صورت تصادفی در دیکشنری ظاهر شده باشند که خوانایی و تحلیل آن را دشوار می‌کند. در این مرحله، با استفاده از تابع <code>sort_inverted_index</code>، نمایه معکوس بر اساس کلید واژه‌ها به ترتیب الفبایی مرتب می‌شود.
  </p>

  <p>
    برای این کار از ساختار <code>OrderedDict</code> از کتابخانه <code>collections</code> استفاده می‌شود تا ترتیب مرتب‌سازی حفظ گردد. این عملیات باعث می‌شود فایل خروجی نهایی، ساختار منظم‌تری داشته باشد و درک و تحلیل آن برای کاربران یا سیستم‌های دیگر آسان‌تر باشد.
  </p>

</div>

## 2- روش اول توکن‌سازی اولیه با حذف نویز و ریشه‌یابی کلمات
"""

def tokenizer(text):
    text = text.lower()
    text = re.sub(r'<[^>]+>', ' ', text)
    text = re.sub(r'[^a-z\s]', '', text)
    tokens = text.split()
    tokens = [token for token in tokens if 2 < len(token) < 20]
    return [stemmer.stem(token) for token in tokens if token not in stopwords]

"""<div dir="rtl" style="font-family: Vazirmatn, Tahoma; font-size:17px; line-height:2; text-align:right; background:#ffffff; border-radius:10px; padding:20px; border:1px solid #ccc; margin-bottom:15px;">

  <h3 style="color:#2c3e50;">توکن‌سازی اولیه با حذف نویز و ریشه‌یابی کلمات</h3>

  <p>
    تابع <code>tokenizer</code> برای پاک‌سازی و آماده‌سازی متون طراحی شده و شامل چند مرحله متوالی است. ابتدا تمام حروف متن ورودی به حالت کوچک تبدیل می‌شوند تا از تفاوت بین حروف بزرگ و کوچک جلوگیری شود. سپس با استفاده از عبارات منظم، تگ‌های HTML و هر نوع کاراکتر غیرحرفی حذف می‌گردد. بعد از آن، متن به مجموعه‌ای از کلمات جدا از هم (توکن‌ها) تقسیم می‌شود. کلماتی که طول آن‌ها کمتر از ۳ حرف یا بیشتر از ۲۰ حرف باشد، فیلتر می‌شوند. در نهایت، واژه‌های پرتکرار و بی‌معنی که در فایل stopwords تعریف شده‌اند کنار گذاشته شده و بقیه توکن‌ها با استفاده از الگوریتم استمر پرتر ریشه‌یابی می‌شوند.
  </p>

</div>

"""

with open("stopwords/english.txt", "r") as f:
    stopwords = set(f.read().lower().split())

stemmer = PorterStemmer()

"""<div dir="rtl" style="font-family: Vazirmatn, Tahoma; font-size:17px; line-height:2; text-align:right; background:#ffffff; border-radius:10px; padding:20px; border:1px solid #ccc; margin-bottom:15px;">

  <h3 style="color:#2c3e50;">بارگذاری کلمات توقف و آماده‌سازی ریشه‌یاب</h3>

  <p>
    در این بخش، ابتدا فایلی شامل کلمات توقف (Stopwords) که معمولاً در پردازش زبان طبیعی نادیده گرفته می‌شوند، از مسیر <code>stopwords/english.txt</code> باز شده و محتویات آن خوانده می‌شود. این کلمات به صورت حروف کوچک و در قالب یک مجموعه (set) ذخیره می‌شوند تا عملیات بررسی حضور کلمات در آن با سرعت بیشتری انجام گیرد. سپس، شیء مربوط به الگوریتم <code>PorterStemmer</code> ساخته می‌شود تا در مراحل بعدی برای ریشه‌یابی کلمات مورد استفاده قرار گیرد.
  </p>

</div>

"""

first_method = copy.deepcopy(all_articles)
tokenize_articles(first_method ,tokenizer)

"""<div dir="rtl" style="font-family: Vazirmatn, Tahoma; font-size:17px; line-height:2; text-align:right; background:#ffffff; border-radius:10px; padding:20px; border:1px solid #ccc; margin-bottom:15px;">

  <h3 style="color:#2c3e50;">ایجاد نسخه کپی از داده‌ها و اعمال توکن‌سازی</h3>

  <p>
    برای جلوگیری از تغییر مستقیم داده‌های اصلی، ابتدا با استفاده از تابع <code>copy.deepcopy</code> یک نسخه‌ی کامل و مستقل از دیکشنری <code>all_articles</code> تهیه می‌شود و در متغیری به نام <code>first_method</code> ذخیره می‌گردد. سپس روی این نسخه، تابع <code>tokenize_articles</code> اعمال می‌شود که وظیفه‌ی اجرای تابع توکن‌ساز تعریف‌شده را برای هر مقاله در دیکشنری بر عهده دارد. این فرآیند باعث می‌شود هر مقاله به لیستی از توکن‌های پردازش‌شده تبدیل شود.
  </p>

</div>

"""

print_sample_dic(first_method , 15 , 31)

"""<div dir="rtl" style="font-family: Vazirmatn, Tahoma; font-size:17px; line-height:2; text-align:right; background:#ffffff; border-radius:10px; padding:20px; border:1px solid #ccc; margin-bottom:15px;">

  <h3 style="color:#2c3e50;">نمایش خروجی نمونه از مقالات توکن‌شده</h3>

  <p>
    تابع <code>print_sample_dic</code> جهت بررسی بصری نتایج توکن‌سازی بر روی بازه‌ای از مقالات استفاده می‌شود. در این مرحله، مقالاتی با شناسه‌های بین ۱۵ تا ۳۱ از دیکشنری <code>first_method</code> که شامل نسخه‌ی توکن‌شده‌ی مقالات است، چاپ می‌گردند. این بازبینی کمک می‌کند صحت عملکرد تابع توکن‌ساز بررسی شود و در صورت وجود هرگونه اشکال در نحوه پاک‌سازی یا ریشه‌یابی واژه‌ها، سریع‌تر شناسایی گردد.
  </p>

</div>

"""

save_dict_to_csv(first_method, "output/first_method_output_tokens.csv")

"""<div dir="rtl" style="font-family: Vazirmatn, Tahoma; font-size:17px; line-height:2; text-align:right; background:#ffffff; border-radius:10px; padding:20px; border:1px solid #ccc; margin-bottom:15px;">

  <h3 style="color:#2c3e50;">ذخیره‌سازی خروجی توکن‌شده در قالب فایل CSV</h3>

  <p>
    پس از انجام عملیات توکن‌سازی روی مقالات، خروجی حاصل با استفاده از تابع <code>save_dict_to_csv</code> در فایل <code>first_method_output_tokens.csv</code> ذخیره می‌شود. این فایل در مسیر <code>output</code> قرار گرفته و شامل اطلاعات ساختاریافته‌ای از هر مقاله به همراه لیست توکن‌های آن است. چنین ذخیره‌سازی‌ای علاوه بر فراهم کردن امکان بررسی دقیق‌تر، امکان استفاده از داده‌ها را در مراحل بعدی پروژه یا ابزارهای دیگر تحلیل فراهم می‌سازد.
  </p>

</div>

"""

matrix = build_inverted_index(first_method)

"""<div dir="rtl" style="font-family: Vazirmatn, Tahoma; font-size:17px; line-height:2; text-align:right; background:#ffffff; border-radius:10px; padding:20px; border:1px solid #ccc; margin-bottom:15px;">

  <h3 style="color:#2c3e50;">ساخت نمایه معکوس از مقالات توکن‌شده</h3>

  <p>
    در این بخش، از تابع <code>build_inverted_index</code> برای ایجاد ساختار نمایه معکوس استفاده شده است. این ساختار داده‌ای، هر واژه را به لیستی از اسناد (مقالات) مرتبط می‌کند که آن واژه در آن‌ها ظاهر شده است. ورودی تابع، دیکشنری <code>first_method</code> است که شامل نسخه‌ی توکن‌شده‌ی مقالات می‌باشد. نمایه معکوس به ازای هر واژه، شناسه‌ی مقالاتی را که آن واژه در آن‌ها وجود دارد به همراه تعداد تکرار آن ذخیره می‌کند و در متغیری به نام <code>matrix</code> نگهداری می‌شود.
  </p>

</div>

"""

print_sample_dic(matrix , 0 , 31)

"""<div dir="rtl" style="font-family: Vazirmatn, Tahoma; font-size:17px; line-height:2; text-align:right; background:#ffffff; border-radius:10px; padding:20px; border:1px solid #ccc; margin-bottom:15px;">

  <h3 style="color:#2c3e50;">نمایش اولیه از نمایه معکوس ساخته‌شده</h3>

  <p>
    با اجرای تابع <code>print_sample_dic</code> بر روی متغیر <code>matrix</code>، نمایی از ۳۱ واژه‌ی ابتدایی در نمایه معکوس چاپ می‌شود. این نمایش شامل واژه، شناسه‌ی مقالاتی که در آن ظاهر شده‌اند، و همچنین تعداد دفعات تکرار آن واژه در هر مقاله است. این بازبینی به توسعه‌دهنده کمک می‌کند تا اطمینان حاصل کند که نمایه‌سازی به‌درستی انجام شده و ساختار داده‌ای ایجادشده، اطلاعات مورد انتظار را در خود جای داده است.
  </p>

</div>

"""

sorted_matrix = sort_inverted_index(matrix)

"""<div dir="rtl" style="font-family: Vazirmatn, Tahoma; font-size:17px; line-height:2; text-align:right; background:#ffffff; border-radius:10px; padding:20px; border:1px solid #ccc; margin-bottom:15px;">

  <h3 style="color:#2c3e50;">مرتب‌سازی نمایه معکوس بر اساس واژه‌ها</h3>

  <p>
    پس از تولید نمایه معکوس اولیه، در این بخش با استفاده از تابع <code>sort_inverted_index</code> اقدام به مرتب‌سازی نمایه انجام می‌شود. این تابع کلیدهای دیکشنری نمایه را که همان واژه‌ها هستند، به‌صورت الفبایی مرتب کرده و نتیجه را در متغیری جدید به نام <code>sorted_matrix</code> ذخیره می‌کند. مرتب‌سازی نمایه باعث می‌شود تحلیل‌های بعدی ساده‌تر، خواناتر و منظم‌تر انجام شود؛ به‌ویژه هنگام نمایش یا ذخیره‌سازی نهایی داده‌ها.
  </p>

</div>

"""

save_dict_to_csv(sorted_matrix, "output/first_method_output_words.csv")

"""<div dir="rtl" style="font-family: Vazirmatn, Tahoma; font-size:17px; line-height:2; text-align:right; background:#ffffff; border-radius:10px; padding:20px; border:1px solid #ccc; margin-bottom:15px;">

  <h3 style="color:#2c3e50;">ذخیره نمایه معکوس مرتب‌شده در فایل CSV</h3>

  <p>
    در این مرحله، نمایه معکوس مرتب‌شده که شامل واژه‌ها به همراه لیست اسناد و فراوانی آن‌ها است، توسط تابع <code>save_dict_to_csv</code> در قالب یک فایل CSV ذخیره می‌شود. این فایل با نام <code>first_method_output_words.csv</code> در پوشه <code>output</code> قرار می‌گیرد و ساختاری قابل استفاده برای تحلیل‌های بعدی یا گزارش‌دهی فراهم می‌آورد.
  </p>

</div>

"""

print_sample_dic(sorted_matrix , 0 , 31)

"""<div dir="rtl" style="font-family: Vazirmatn, Tahoma; font-size:17px; line-height:2; text-align:right; background:#ffffff; border-radius:10px; padding:20px; border:1px solid #ccc; margin-bottom:15px;">

  <h3 style="color:#2c3e50;">نمایش نمونه‌ای از نمایه معکوس مرتب‌شده</h3>

  <p>
    در این بخش، با استفاده از تابع <code>print_sample_dic</code>، نمونه‌ای از ۳۱ ورودی ابتدایی نمایه معکوس مرتب‌شده چاپ می‌شود. این نمایش کمک می‌کند تا صحت ساختار نمایه و اطلاعات ذخیره شده درباره واژه‌ها و اسناد مرتبط به‌طور ملموس مشاهده شود و هرگونه ایراد احتمالی در داده‌ها شناسایی گردد.
  </p>

</div>

## ماتریس اسپارس
"""

docs = 22
word2index = {word: i for i, word in enumerate(sorted_matrix.keys())}
words = len(word2index)
tf_matrix = np.zeros((words, docs), dtype=float)

for word, posting_list in sorted_matrix.items():
    row = word2index[word]
    for doc_id, tf in posting_list.data_list:
        tf_matrix[row][doc_id] = 1 + np.log(tf)

print(tf_matrix)

"""<div dir="rtl" style="font-family: Vazirmatn, Tahoma; font-size:17px; line-height:2; text-align:right; background:#ffffff; border-radius:10px; padding:20px; border:1px solid #ccc; margin-bottom:15px;">

  <h3 style="color:#2c3e50;">ساخت ماتریس TF نرمال‌شده (TF Matrix)</h3>

  <p>
    در این بخش، با توجه به تعداد کل اسناد (۲۲ سند)، ابتدا یک نگاشت از واژه‌ها به اندیس‌های عددی ساخته می‌شود تا بتوان ماتریس TF (Term Frequency) را به صورت عددی ایجاد کرد. سپس ماتریسی با ابعاد تعداد واژه‌ها در تعداد اسناد ساخته شده که در آن هر خانه نشان‌دهنده فراوانی وزن‌دار یک واژه در یک سند است.
  </p>
  
  <p>
    برای مقداردهی ماتریس، از لگاریتم وزن‌دهی استفاده شده است که به صورت <code>1 + log(tf)</code> محاسبه می‌شود؛ این کار کمک می‌کند تأثیر کلمات بسیار پرتکرار کاهش یابد و ماتریس تعادلی‌تر شود. در نهایت، ماتریس TF نرمال‌شده چاپ می‌شود تا نتیجه نهایی برای تحلیل‌های بعدی آماده باشد.
  </p>

</div>

"""

df = pd.DataFrame(tf_matrix, index=word2index.keys())
df.to_csv("output/first_tf_matrix.csv")

"""<div dir="rtl" style="font-family: Vazirmatn, Tahoma; font-size:17px; line-height:2; text-align:right; background:#ffffff; border-radius:10px; padding:20px; border:1px solid #ccc; margin-bottom:15px;">

  <h3 style="color:#2c3e50;">ذخیره ماتریس TF در فایل CSV</h3>

  <p>
    در این مرحله، ماتریس فراوانی وزن‌دار واژه‌ها (TF Matrix) به یک دیتافریم <code>pandas</code> تبدیل می‌شود که ردیف‌های آن نشان‌دهنده واژه‌ها و ستون‌های آن معرف شناسه اسناد است. سپس این دیتافریم در قالب یک فایل CSV با نام <code>first_tf_matrix.csv</code> در پوشه <code>output</code> ذخیره می‌شود تا امکان تحلیل و بررسی داده‌ها به صورت جدولی و در محیط‌های دیگر فراهم گردد.
  </p>

</div>

"""

df = pd.DataFrame(tf_matrix, index=word2index.keys())

limited_df = df.iloc[:, :]
plt.figure(figsize=(4, 20))
sns.heatmap(limited_df, cmap="YlGnBu", annot=False , yticklabels=False)
plt.title("TF Log Heatmap for Top Words")
plt.xlabel("Document ID")
plt.ylabel("Words")

plt.tight_layout()
plt.show()

"""<div dir="rtl" style="font-family: Vazirmatn, Tahoma; font-size:17px; line-height:2; text-align:right; background:#ffffff; border-radius:10px; padding:20px; border:1px solid #ccc; margin-bottom:15px;">

  <h3 style="color:#2c3e50;">ترسیم نمودار حرارتی (Heatmap) ماتریس TF</h3>

  <p>
    در این قسمت، ماتریس TF که قبلاً ساخته شده بود، به یک DataFrame پانداس تبدیل شده و سپس با استفاده از کتابخانه <code>seaborn</code> نمودار حرارتی آن رسم می‌شود. محور افقی نمایانگر شناسه اسناد و محور عمودی واژه‌ها است.
  </p>

  <p>
    این نمودار حرارتی به صورت رنگی و در قالب طیف رنگی <code>YlGnBu</code> نمایش داده شده تا الگوهای فراوانی واژه‌ها در اسناد مختلف به طور بصری قابل درک باشد. برای خوانایی بهتر، برچسب‌های محور y حذف شده‌اند و اندازه نمودار به گونه‌ای تنظیم شده که تمامی واژه‌ها قابل مشاهده باشند.
  </p>

</div>

"""

pca = PCA(n_components=2)
reduced_data = pca.fit_transform(tf_matrix)

plt.scatter(reduced_data[:, 0], reduced_data[:, 1], alpha=0.7)
plt.title("2D PCA Projection of TF Matrix")
plt.xlabel("Principal Component 1")
plt.ylabel("Principal Component 2")
plt.show()

"""<div dir="rtl" style="font-family: Vazirmatn, Tahoma; font-size:17px; line-height:2; text-align:right; background:#ffffff; border-radius:10px; padding:20px; border:1px solid #ccc; margin-bottom:15px;">

  <h3 style="color:#2c3e50;">کاهش ابعاد ماتریس TF با روش PCA و ترسیم نمودار پراکندگی دو بعدی</h3>

  <p>
    در این مرحله با استفاده از تکنیک تحلیل مؤلفه‌های اصلی (PCA) تعداد ابعاد ماتریس TF که بسیار بزرگ و پیچیده است به دو بعد کاهش داده می‌شود. این کار کمک می‌کند تا الگوهای مهم و ساختار کلی داده‌ها در فضای دوبعدی قابل مشاهده و تحلیل باشد.
  </p>

  <p>
    سپس داده‌های کاهش‌یافته در یک نمودار پراکندگی دو بعدی رسم می‌شوند که هر نقطه نمایانگر یک سند است. محورهای نمودار به ترتیب مولفه‌های اصلی اول و دوم هستند. این نمایش تصویری به درک بهتر شباهت‌ها و تفاوت‌های میان اسناد کمک می‌کند.
  </p>

</div>

## 3-(روش دوم) WordNetتوکن‌سازی مبتنی بر
"""

def is_valid_word(word):
    return wordnet.synsets(word) != []

"""<div dir="rtl" style="font-family: Vazirmatn, Tahoma; font-size:17px; line-height:2; text-align:right; background:#ffffff; border-radius:10px; padding:20px; border:1px solid #ccc; margin-bottom:15px;">

  <h3 style="color:#2c3e50;">تابع بررسی معتبر بودن واژه‌ها</h3>

  <p>
    این تابع با استفاده از پایگاه داده واژگانی WordNet بررسی می‌کند که آیا واژه ورودی در این دیکشنری معنایی وجود دارد یا خیر. اگر مجموعه‌ای از معانی (synsets) برای واژه یافت شود، آن واژه به عنوان واژه معتبر شناخته می‌شود و در فرآیندهای بعدی مانند توکن‌سازی و فیلتر کردن متون نگهداری می‌گردد.
  </p>

</div>

"""

def tokenizer_by_dict(text):
    text = text.lower()
    text = re.sub(r'<[^>]+>', ' ', text)
    text = re.sub(r'[^a-z\s]', '', text)
    tokens = text.split()
    tokens = [token for token in tokens if 2 < len(token) < 20]
    valid_tokens = [token for token in tokens if is_valid_word(token)]
    return [stemmer.stem(token) for token in valid_tokens if token not in stopwords]

"""<div dir="rtl" style="font-family: Vazirmatn, Tahoma; font-size:17px; line-height:2; text-align:right; background:#ffffff; border-radius:10px; padding:20px; border:1px solid #ccc; margin-bottom:15px;">

  <h3 style="color:#2c3e50;">تابع توکن‌سازی با اعتبارسنجی واژه‌ها</h3>

  <p>
    این تابع متن ورودی را ابتدا به حروف کوچک تبدیل کرده و تگ‌های HTML و کاراکترهای غیرحروفی را حذف می‌کند. سپس واژه‌ها به‌صورت اولیه جدا شده و فیلتر می‌شوند تا تنها واژه‌هایی با طول مناسب (بین ۳ تا ۲۰ حرف) نگهداری شوند.
  </p>

  <p>
    در مرحله بعد، هر واژه توسط تابع <code>is_valid_word</code> اعتبارسنجی شده و فقط واژه‌های معنادار (یافت شده در پایگاه WordNet) حفظ می‌شوند. نهایتاً واژه‌های معتبر پس از حذف <code>stopwords</code>، ریشه‌یابی شده و بازگردانده می‌شوند.
  </p>

</div>

"""

sec_method = copy.deepcopy(all_articles)

"""<div dir="rtl" style="font-family: Vazirmatn, Tahoma; font-size:17px; line-height:2; text-align:right; background:#ffffff; border-radius:10px; padding:20px; border:1px solid #ccc; margin-bottom:15px;">

  <h3 style="color:#2c3e50;">نسخه‌برداری عمیق از داده‌های اصلی</h3>

  <p>
    برای جلوگیری از تغییرات ناخواسته روی داده‌های اصلی <code>all_articles</code>، از روش <code>deepcopy</code> استفاده شده است تا یک کپی مستقل و کامل از کل ساختار داده‌ها ایجاد شود. این نسخه کپی‌شده به متغیر <code>sec_method</code> اختصاص داده شده و مراحل پردازش بعدی روی آن انجام می‌شود.
  </p>

</div>


"""

print_sample_dic(sec_method , 15 , 31)

"""<div dir="rtl" style="font-family: Vazirmatn, Tahoma; font-size:17px; line-height:2; text-align:right; background:#ffffff; border-radius:10px; padding:20px; border:1px solid #ccc; margin-bottom:15px;">

  <h3 style="color:#2c3e50;">نمایش نمونه‌ای از داده‌های پردازش شده</h3>

  <p>
    با اجرای تابع <code>print_sample_dic</code> نمونه‌ای از داده‌های توکن‌شده در بازه مشخص‌شده (از ۱۵ تا ۳۱) به صورت مرتب نمایش داده می‌شود. این نمایش کمک می‌کند تا صحت و کیفیت مراحل پردازش و توکن‌سازی داده‌ها به صورت دستی بررسی شود.
  </p>

</div>

"""

tokenize_articles(sec_method ,tokenizer_by_dict)

"""<div dir="rtl" style="font-family: Vazirmatn, Tahoma; font-size:17px; line-height:2; text-align:right; background:#ffffff; border-radius:10px; padding:20px; border:1px solid #ccc; margin-bottom:15px;">

  <h3 style="color:#2c3e50;">اجرای فرآیند توکن‌سازی روی مقالات</h3>

  <p>
    در این مرحله، با استفاده از تابع <code>tokenize_articles</code>، متن تمامی مقالات موجود در نسخه کپی‌شده <code>sec_method</code>، با الگوریتم توکن‌سازی تعریف‌شده در تابع <code>tokenizer_by_dict</code> پردازش می‌شود. این عملیات شامل پاک‌سازی، فیلتر کردن و ریشه‌یابی واژه‌ها بوده و نتیجه آن مجموعه‌ای از توکن‌های معتبر برای هر مقاله است.
  </p>

</div>

"""

print_sample_dic(sec_method , 15 , 31)

"""<div dir="rtl" style="font-family: Vazirmatn, Tahoma; font-size:17px; line-height:2; text-align:right; background:#ffffff; border-radius:10px; padding:20px; border:1px solid #ccc; margin-bottom:15px;">

  <h3 style="color:#2c3e50;">نمایش نمونه‌ای از مقالات پردازش شده</h3>

  <p>
    با اجرای دستور <code>print_sample_dic(sec_method, 15, 31)</code> نمونه‌ای از مقالات پردازش‌شده و توکن‌شده در بازه مشخص شده (از شماره ۱۵ تا ۳۱) به صورت خلاصه و مرتب نمایش داده می‌شود. این کار به منظور بررسی صحت فرآیند توکن‌سازی و اعتبار داده‌ها انجام می‌شود.
  </p>

</div>

"""

save_dict_to_csv(sec_method, "output/second_method_output_tokens.csv")

"""<div dir="rtl" style="font-family: Vazirmatn, Tahoma; font-size:17px; line-height:2; text-align:right; background:#ffffff; border-radius:10px; padding:20px; border:1px solid #ccc; margin-bottom:15px;">

  <h3 style="color:#2c3e50;">ذخیره‌سازی توکن‌های استخراج شده در فایل CSV</h3>

  <p>
    در این بخش، داده‌های توکن‌شده حاصل از روش دوم (توکن‌سازی با استفاده از دیکشنری) با استفاده از تابع <code>save_dict_to_csv</code> در قالب فایل CSV در مسیر <code>output/second_method_output_tokens.csv</code> ذخیره می‌شوند. این کار به منظور نگهداری و استفاده آسان‌تر از نتایج پردازش انجام شده است.
  </p>

</div>

"""

words = build_inverted_index(sec_method)

"""<div dir="rtl" style="font-family: Vazirmatn, Tahoma; font-size:17px; line-height:2; text-align:right; background:#ffffff; border-radius:10px; padding:20px; border:1px solid #ccc; margin-bottom:15px;">

  <h3 style="color:#2c3e50;">ساخت نمایه معکوس از توکن‌های پردازش شده</h3>

  <p>
    در این مرحله، با استفاده از تابع <code>build_inverted_index</code>، نمایه معکوسی بر پایه توکن‌های استخراج شده از مقالات در نسخه <code>sec_method</code> ساخته می‌شود. این نمایه شامل نگاشت هر واژه به شناسه‌ سندهایی است که واژه در آن‌ها وجود دارد، همراه با فراوانی آن در هر سند.
  </p>

</div>

"""

print_sample_dic(words , 0 , 31)

"""<div dir="rtl" style="font-family: Vazirmatn, Tahoma; font-size:17px; line-height:2; text-align:right; background:#ffffff; border-radius:10px; padding:20px; border:1px solid #ccc; margin-bottom:15px;">

  <h3 style="color:#2c3e50;">نمایش نمونه‌ای از نمایه معکوس مرتب‌شده</h3>

  <p>
    با اجرای تابع <code>print_sample_dic(words, 0, 31)</code>، نمونه‌ای از نمایه معکوس مرتب‌شده (از اولین تا سی و یکمین واژه) به صورت خلاصه نمایش داده می‌شود. این مرحله برای بررسی دقیق‌تر و اطمینان از صحت ساختار نمایه معکوس انجام می‌شود.
  </p>

</div>

"""

sorted_words = sort_inverted_index(words)

"""<div dir="rtl" style="font-family: Vazirmatn, Tahoma; font-size:17px; line-height:2; text-align:right; background:#ffffff; border-radius:10px; padding:20px; border:1px solid #ccc; margin-bottom:15px;">

  <h3 style="color:#2c3e50;">مرتب‌سازی نمایه معکوس</h3>

  <p>
    در این مرحله، نمایه معکوس ساخته شده با استفاده از تابع <code>sort_inverted_index</code> بر اساس کلیدهای واژه‌ای به صورت الفبایی مرتب می‌شود. این کار باعث افزایش سرعت جستجو و سهولت در تحلیل‌های بعدی می‌گردد.
  </p>

</div>

"""

print_sample_dic(sorted_words , 0 , 31)

"""<div dir="rtl" style="font-family: Vazirmatn, Tahoma; font-size:17px; line-height:2; text-align:right; background:#ffffff; border-radius:10px; padding:20px; border:1px solid #ccc; margin-bottom:15px;">

  <h3 style="color:#2c3e50;">نمایش نمونه‌ای از نمایه معکوس مرتب‌شده روش دوم</h3>

  <p>
    با اجرای تابع <code>print_sample_dic(sorted_words, 0, 31)</code> نمونه‌ای از نمایه معکوس مرتب‌شده که مربوط به روش دوم است، در بازه مشخص شده نمایش داده می‌شود. این مرحله به منظور ارزیابی و بررسی دقیق‌تر داده‌های نمایه معکوس کاربرد دارد.
  </p>

</div>

"""

save_dict_to_csv(sorted_words, "output/second_method_output_words.csv")

"""<div dir="rtl" style="font-family: Vazirmatn, Tahoma; font-size:17px; line-height:2; text-align:right; background:#ffffff; border-radius:10px; padding:20px; border:1px solid #ccc; margin-bottom:15px;">

  <h3 style="color:#2c3e50;">ذخیره نمایه معکوس روش دوم در فایل CSV</h3>

  <p>
    در این مرحله، نمایه معکوس مرتب‌شده که حاصل روش دوم توکن‌سازی است، با استفاده از تابع <code>save_dict_to_csv</code> به صورت فایل CSV ذخیره می‌شود. این فایل در مسیر <code>output/second_method_output_words.csv</code> قرار می‌گیرد و امکان استفاده و بررسی داده‌ها در نرم‌افزارهای دیگر را فراهم می‌کند.
  </p>

</div>

## 4- NLP روش سوم
"""

third_method = copy.deepcopy(all_articles)

"""<div dir="rtl" style="font-family: Vazirmatn, Tahoma; font-size:17px; line-height:2; text-align:right; background:#ffffff; border-radius:10px; padding:20px; border:1px solid #ccc; margin-bottom:15px;">

  <h3 style="color:#2c3e50;">ایجاد نسخه‌ای مستقل از داده‌های اصلی </h3>

  <p>
    در این مرحله، با استفاده از تابع <code>copy.deepcopy</code>، یک کپی عمیق (مستقل و بدون ارجاع به داده‌های اولیه) از دیکشنری <code>all_articles</code> ساخته می‌شود. این نسخه کپی شده با نام <code>third_method</code> برای پردازش‌های روش سوم استفاده خواهد شد تا از تغییرات ناخواسته روی داده‌های اصلی جلوگیری شود.
  </p>

</div>

"""

print_sample_dic(third_method , 15 , 17)

"""<div dir="rtl" style="font-family: Vazirmatn, Tahoma; font-size:17px; line-height:2; text-align:right; background:#ffffff; border-radius:10px; padding:20px; border:1px solid #ccc; margin-bottom:15px;">

  <h3 style="color:#2c3e50;">نمایش نمونه‌ای از داده‌ها </h3>

  <p>
    با اجرای دستور <code>print_sample_dic(third_method, 15, 17)</code>، نمونه‌ای از مقالات پردازش‌شده در بازه شماره ۱۵ تا ۱۷ به صورت خلاصه نمایش داده می‌شود. این نمایش به منظور ارزیابی صحت داده‌ها و بررسی فرآیند توکن‌سازی در روش سوم کاربرد دارد.
  </p>

</div>

"""

from keybert import KeyBERT

kw_model = KeyBERT()

def extract_meaningful_tokens(article_obj):
    text = f"{article_obj.title} {article_obj.body}"
    keywords = kw_model.extract_keywords(text, top_n=30, stop_words='english')
    return [kw for kw, score in keywords]

for article_id, article in third_method.items():
    article.tokens = extract_meaningful_tokens(article)
    article.body = ""

"""<div dir="rtl" style="font-family: Vazirmatn, Tahoma; font-size:17px; line-height:2; text-align:right; background:#ffffff; border-radius:10px; padding:20px; border:1px solid #ccc; margin-bottom:15px;">

  <h3 style="color:#2c3e50;">استخراج کلمات کلیدی معنادار با استفاده از مدل KeyBERT</h3>

  <p>
    در این بخش، با بهره‌گیری از کتابخانه <code>KeyBERT</code>، مدل <code>kw_model</code> ساخته شده است تا بتوان کلمات کلیدی مهم و معنادار را از متن ترکیبی عنوان و بدنه هر مقاله استخراج کرد.
  </p>

  <p>
    تابع <code>extract_meaningful_tokens</code> متن مقاله را دریافت کرده و با استفاده از مدل کلیدواژه‌ها را استخراج می‌کند؛ سپس فقط کلمات کلیدی را به صورت لیستی بازمی‌گرداند.
  </p>

  <p>
    در ادامه، برای هر مقاله در داده‌های <code>third_method</code> این عملیات انجام شده و کلمات کلیدی به عنوان توکن‌ها جایگزین می‌شوند. همچنین برای کاهش حجم داده، متن بدنه مقاله خالی می‌شود.
  </p>

</div>

"""

print_sample_dic(third_method , 15 , 31)

"""<div dir="rtl" style="font-family: Vazirmatn, Tahoma; font-size:17px; line-height:2; text-align:right; background:#ffffff; border-radius:10px; padding:20px; border:1px solid #ccc; margin-bottom:15px;">

  <h3 style="color:#2c3e50;">نمایش نمونه‌ای از مقالات پردازش‌شده </h3>

  <p>
    با اجرای دستور <code>print_sample_dic(third_method, 15, 31)</code>، نمونه‌ای از مقالات پردازش شده در بازه مشخص شده نمایش داده می‌شود. این نمایش برای بررسی صحت استخراج کلمات کلیدی و وضعیت نهایی توکن‌ها در این روش بسیار مفید است.
  </p>

</div>

"""

save_dict_to_csv(third_method, "output/third_method_output_tokens.csv")
third_matrix = build_inverted_index(third_method)

"""<div dir="rtl" style="font-family: Vazirmatn, Tahoma; font-size:17px; line-height:2; text-align:right; background:#ffffff; border-radius:10px; padding:20px; border:1px solid #ccc; margin-bottom:15px;">

  <h3 style="color:#2c3e50;">ذخیره توکن‌های استخراج‌شده و ساخت نمایه معکوس </h3>

  <p>
    پس از استخراج کلمات کلیدی معنادار، داده‌های توکن‌شده در فایلی با نام <code>third_method_output_tokens.csv</code> ذخیره می‌شوند تا امکان بررسی و استفاده آسان‌تر از نتایج فراهم گردد.
  </p>

  <p>
    سپس با استفاده از تابع <code>build_inverted_index</code>، نمایه معکوس از داده‌های توکن‌شده ساخته می‌شود. این نمایه شامل نگاشت کلمات به اسناد و تعداد وقوع هر کلمه در هر سند است که برای بازیابی اطلاعات بسیار حیاتی است.
  </p>

</div>

"""

print_sample_dic(third_matrix , 0 , 31)

"""<div dir="rtl" style="font-family: Vazirmatn, Tahoma; font-size:17px; line-height:2; text-align:right; background:#ffffff; border-radius:10px; padding:20px; border:1px solid #ccc; margin-bottom:15px;">

  <h3 style="color:#2c3e50;">نمایش نمونه‌ای از نمایه معکوس ساخته‌شده</h3>

  <p>
    با اجرای دستور <code>print_sample_dic(third_matrix, 0, 31)</code>، نمونه‌ای از نمایه معکوس ایجاد شده با استفاده از روش استخراج کلیدواژه‌های معنادار نمایش داده می‌شود. این نمایش برای بررسی صحت نمایه و اطمینان از کیفیت داده‌های بازیابی‌شده اهمیت دارد.
  </p>

</div>

"""

save_dict_to_csv(third_matrix, "output/third_method_output_words_.csv")

"""<div dir="rtl" style="font-family: Vazirmatn, Tahoma; font-size:17px; line-height:2; text-align:right; background:#ffffff; border-radius:10px; padding:20px; border:1px solid #ccc; margin-bottom:15px;">

  <h3 style="color:#2c3e50;">ذخیره نمایه معکوس در فایل CSV</h3>

  <p>
    نمایه معکوس ساخته شده توسط روش استخراج کلمات کلیدی معنادار در فایلی با نام <code>third_method_output_words_.csv</code> ذخیره می‌شود. این کار باعث می‌شود تا نتایج به صورت ساختاریافته و قابل بررسی در نرم‌افزارهای صفحه گسترده قابل دسترسی باشند.
  </p>

</div>

"""

ma = sort_inverted_index(third_matrix)

"""<div dir="rtl" style="font-family: Vazirmatn, Tahoma; font-size:17px; line-height:2; text-align:right; background:#ffffff; border-radius:10px; padding:20px; border:1px solid #ccc; margin-bottom:15px;">

  <h3 style="color:#2c3e50;">مرتب‌سازی نمایه معکوس </h3>

  <p>
    در این مرحله، نمایه معکوس ساخته شده توسط روش استخراج کلمات کلیدی معنادار با استفاده از تابع <code>sort_inverted_index</code> بر اساس کلیدهای واژگان مرتب می‌شود. این مرتب‌سازی باعث می‌شود نمایه ساختاری منظم‌تر و قابل جستجوتر داشته باشد و سرعت بازیابی اطلاعات افزایش یابد.
  </p>

</div>

## 5- تحلیل و مقایسه معیارهای نمایه‌های معکوس
"""

def compute_metrics(index_dict):
    total_terms = len(index_dict)
    total_df = sum(len(pl.doc_ids) for pl in index_dict.values())
    total_ttf = sum(pl.total_tf for pl in index_dict.values())
    return total_terms, total_df, total_ttf

def plot_comparison(methods_dict):
    labels = []
    term_counts = []
    df_sums = []
    ttf_sums = []

    for method_name, index in methods_dict.items():
        labels.append(method_name)
        total_terms, total_df, total_ttf = compute_metrics(index)
        term_counts.append(total_terms)
        df_sums.append(total_df)
        ttf_sums.append(total_ttf)

    x = range(len(labels))
    width = 0.25

    fig, ax = plt.subplots(figsize=(10, 6))

    bars1 = ax.bar([i - width for i in x], term_counts, width=width, label='Unique Terms', color='skyblue')
    bars2 = ax.bar(x, df_sums, width=width, label='Total DF', color='lightgreen')
    bars3 = ax.bar([i + width for i in x], ttf_sums, width=width, label='Total TTF', color='salmon')

    for bars in [bars1, bars2, bars3]:
        for bar in bars:
            height = bar.get_height()
            ax.text(bar.get_x() + bar.get_width() / 2, height + 5, f'{int(height)}',
                    ha='center', va='bottom', fontsize=9)

    ax.set_xticks(x)
    ax.set_xticklabels(labels)
    ax.set_ylabel("Count")
    ax.set_title("Comparison of Inverted Index Methods")
    ax.legend()
    ax.grid(axis='y', linestyle='--', alpha=0.5)

    plt.tight_layout()
    plt.show()

"""<div dir="rtl" style="font-family: Vazirmatn, Tahoma; font-size:17px; line-height:2; text-align:right; background:#ffffff; border-radius:10px; padding:20px; border:1px solid #ccc; margin-bottom:15px;">

  <h3 style="color:#2c3e50;">تحلیل و مقایسه معیارهای نمایه‌های معکوس</h3>

  <p>
    در این بخش، با استفاده از تابع <code>compute_metrics</code>، سه معیار مهم شامل تعداد واژگان منحصربه‌فرد، مجموع فرکانس اسناد (Document Frequency) و مجموع فرکانس کل واژگان (Total Term Frequency) برای هر نمایه معکوس محاسبه می‌شود.
  </p>

  <p>
    سپس با کمک تابع <code>plot_comparison</code>، این معیارها برای هر یک از روش‌های ساخت نمایه معکوس به صورت نمودار میله‌ای نمایش داده می‌شود. این نمودارها به صورت دسته‌ای (Grouped Bar Chart) ارائه شده‌اند تا بتوان به راحتی تفاوت‌ها و شباهت‌های هر روش را در ابعاد مختلف بررسی کرد.
  </p>

  <p style="background:#f9f9f9; border:1px dashed #aaa; padding:12px; border-radius:8px;">
    این تحلیل تصویری کمک می‌کند تا میزان پوشش و عمق داده‌ها در هر روش بهتر درک شود و تصمیم‌گیری درباره انتخاب بهترین روش برای کاربردهای بعدی آسان‌تر گردد.
  </p>

</div>

"""

methods = {
    "Simple": sorted_matrix,
    "Dictionary": sorted_words,
    "ML": third_matrix
}
plot_comparison(methods)

"""<div dir="rtl" style="font-family: Vazirmatn, Tahoma; font-size:17px; line-height:2; text-align:right; background:#ffffff; border-radius:10px; padding:20px; border:1px solid #ccc; margin-bottom:15px;">

  <h3 style="color:#2c3e50;">مقایسه روش‌های مختلف نمایه‌سازی</h3>

  <p>
    در این بخش، سه روش متفاوت برای ساخت نمایه معکوس شامل <strong>Simple</strong> (روش ساده)، <strong>Dictionary</strong> (روش بر پایه دیکشنری) و <strong>ML</strong> (روش مبتنی بر یادگیری ماشین با KeyBERT) به عنوان ورودی به تابع <code>plot_comparison</code> داده شده‌اند.
  </p>

  <p>
    نمودارهای تولید شده به صورت گرافیکی مقادیر کلیدی مانند تعداد واژگان منحصربه‌فرد، مجموع فرکانس اسناد و مجموع فرکانس کل واژگان را برای هر روش نمایش می‌دهند تا بتوان به راحتی نقاط قوت و ضعف هر روش را مشاهده کرد.
  </p>

</div>

"""

def plot_common_vs_uncommon_terms(methods):

    sets = [set(index.keys()) for index in methods.values()]

    common_all = sets[0] & sets[1] & sets[2]

    all_terms = sets[0] | sets[1] | sets[2]

    uncommon_terms = all_terms - common_all

    labels = ['Common in All 3', 'Not in All 3']
    sizes = [len(common_all), len(uncommon_terms)]
    colors = ['#66b3ff', '#ff9999']

    plt.figure(figsize=(8, 8))
    plt.pie(
        sizes,
        labels=[f'{label}: {size} ({size / sum(sizes) * 100:.1f}%)' for label, size in zip(labels, sizes)],
        autopct='%1.1f%%',
        startangle=140,
        colors=colors,
        textprops={'fontsize': 12}
    )
    plt.title("Word Distribution: Common vs Not in All 3", fontsize=14)
    plt.axis('equal')
    plt.tight_layout()
    plt.show()

"""<div dir="rtl" style="font-family: Vazirmatn, Tahoma; font-size:17px; line-height:2; text-align:right; background:#ffffff; border-radius:10px; padding:20px; border:1px solid #ccc; margin-bottom:15px;">

  <h3 style="color:#2c3e50;">تحلیل واژگان مشترک و غیرمشترک بین سه روش</h3>

  <p>
    این بخش با استفاده از تابع <code>plot_common_vs_uncommon_terms</code>، واژگانی که در هر سه روش ساخت نمایه معکوس مشترک هستند را از آن‌هایی که در همه روش‌ها حضور ندارند جدا می‌کند.
  </p>

  <p>
    سپس یک نمودار دایره‌ای (Pie Chart) رسم می‌شود که درصد و تعداد واژگان مشترک و غیرمشترک را به صورت گرافیکی نمایش می‌دهد. این نمودار کمک می‌کند تا میزان همپوشانی و تفاوت واژگان استخراج شده در هر روش به خوبی درک شود.
  </p>

</div>

"""

plot_common_vs_uncommon_terms(methods)

"""<div dir="rtl" style="font-family: Vazirmatn, Tahoma; font-size:17px; line-height:2; text-align:right; background:#ffffff; border-radius:10px; padding:20px; border:1px solid #ccc; margin-bottom:15px;">

  <h3 style="color:#2c3e50;">نمایش واژگان مشترک و غیرمشترک بین سه روش</h3>

  <p>
    با اجرای تابع <code>plot_common_vs_uncommon_terms(methods)</code>، نموداری دایره‌ای (Pie Chart) رسم می‌شود که درصد واژگان مشترک بین هر سه روش ساخت نمایه معکوس را نسبت به واژگان غیرمشترک نشان می‌دهد. این تحلیل بصری به فهم بهتر میزان اشتراک واژگان در روش‌های مختلف کمک می‌کند.
  </p>

</div>

"""

def plot_pairwise_common_vs_uncommon_vertical(methods):
    method_names = list(methods.keys())
    sets = [set(index.keys()) for index in methods.values()]

    pairs = list(combinations(range(len(methods)), 2))

    fig, axes = plt.subplots(len(pairs), 1, figsize=(7, 5 * len(pairs)))
    if len(pairs) == 1:
        axes = [axes]

    for ax, (i, j) in zip(axes, pairs):
        set_i = sets[i]
        set_j = sets[j]

        common = set_i & set_j
        all_terms = set_i | set_j
        uncommon = all_terms - common

        sizes = [len(common), len(uncommon)]
        labels = [
            f"Common ({method_names[i]} & {method_names[j]}): {sizes[0]} ({sizes[0]/sum(sizes)*100:.1f}%)",
            f"Not Common: {sizes[1]} ({sizes[1]/sum(sizes)*100:.1f}%)"
        ]
        colors = ['#66b3ff', '#ff9999']

        ax.pie(
            sizes,
            labels=labels,
            autopct='%1.1f%%',
            startangle=140,
            colors=colors,
            textprops={'fontsize': 12}
        )
        ax.set_title(f"Pairwise: {method_names[i]} vs {method_names[j]}", fontsize=14)
        ax.axis('equal')

    plt.tight_layout()
    plt.show()

methods = {
    "Simple": sorted_matrix,
    "Dictionary": sorted_words,
    "ML": third_matrix
}

plot_pairwise_common_vs_uncommon_vertical(methods)

"""<div dir="rtl" style="font-family: Vazirmatn, Tahoma; font-size:17px; line-height:2; text-align:right; background:#ffffff; border-radius:10px; padding:20px; border:1px solid #ccc; margin-bottom:15px;">

  <h3 style="color:#2c3e50;">تحلیل مقایسه‌ای زوجی واژگان مشترک و غیرمشترک</h3>

  <p>
    در این مرحله، با استفاده از تابع <code>plot_pairwise_common_vs_uncommon_vertical</code>، مقایسه‌ای زوجی بین هر دو روش از سه روش ساخت نمایه معکوس انجام شده است. این مقایسه شامل محاسبه تعداد واژگان مشترک و غیرمشترک بین هر جفت روش می‌باشد.
  </p>

  <p>
    خروجی بصری به صورت نمودارهای دایره‌ای (Pie Charts) نمایش داده می‌شود که درصد و تعداد واژگان مشترک و غیرمشترک برای هر جفت روش را نشان می‌دهد. این تحلیل کمک می‌کند تا نقاط اشتراک و تمایز بین روش‌ها به طور دقیق‌تر بررسی شود.
  </p>

</div>

"""

def plot_term_overlap_matrix(methods):
    names = list(methods.keys())
    term_sets = {name: set(index.keys()) for name, index in methods.items()}

    overlap_matrix = pd.DataFrame(index=names, columns=names)

    for i in names:
        for j in names:
            if i == j:
                overlap_matrix.loc[i, j] = len(term_sets[i])
            else:
                overlap_matrix.loc[i, j] = len(term_sets[i].intersection(term_sets[j]))

    overlap_matrix = overlap_matrix.astype(int)

    plt.figure(figsize=(8, 6))
    sns.heatmap(overlap_matrix, annot=True, fmt='d', cmap='Blues', cbar=True)
    plt.title("Term Overlap Between Methods", fontsize=14)
    plt.xlabel("Method")
    plt.ylabel("Method")
    plt.tight_layout()
    plt.show()

"""<div dir="rtl" style="font-family: Vazirmatn, Tahoma; font-size:17px; line-height:2; text-align:right; background:#ffffff; border-radius:10px; padding:20px; border:1px solid #ccc; margin-bottom:15px;">

  <h3 style="color:#2c3e50;">ماتریس همپوشانی واژگان بین روش‌ها</h3>

  <p>
    در این قسمت، با استفاده از تابع <code>plot_term_overlap_matrix</code>، ماتریسی از همپوشانی واژگان استخراج شده توسط هر روش ساخته شده است. این ماتریس، تعداد واژگان مشترک بین هر جفت روش را نمایش می‌دهد و به صورت یک <strong>نقشه حرارتی (Heatmap)</strong> رسم می‌شود.
  </p>

  <p>
    قطر اصلی ماتریس نشان‌دهنده تعداد کل واژگان منحصربه‌فرد هر روش است و سایر خانه‌ها تعداد واژگان مشترک بین دو روش خاص را نشان می‌دهند. این تحلیل تصویری کمک می‌کند تا میزان همپوشانی و تفاوت بین روش‌های مختلف نمایه‌سازی به راحتی ارزیابی شود.
  </p>

</div>

"""

plot_term_overlap_matrix(methods)

"""<div dir="rtl" style="font-family: Vazirmatn, Tahoma; font-size:17px; line-height:2; text-align:right; background:#ffffff; border-radius:10px; padding:20px; border:1px solid #ccc; margin-bottom:15px;">

  <h3 style="color:#2c3e50;">نمایش همپوشانی واژگان بین روش‌های مختلف</h3>

  <p>
    در این بخش، با اجرای تابع <code>plot_term_overlap_matrix(methods)</code>، ماتریس همپوشانی واژگان میان روش‌های مختلف نمایه‌سازی رسم شده است.
  </p>

  <p>
    این ماتریس تعداد واژگان منحصربه‌فرد هر روش را در قطر اصلی و تعداد واژگان مشترک بین هر دو روش را در خانه‌های مربوطه نمایش می‌دهد. نمودار به صورت یک نقشه حرارتی (Heatmap) ارائه شده تا دید بهتری از میزان اشتراک و تفاوت بین روش‌ها فراهم آورد.
  </p>

</div>

"""